name: 'Sanity'
on:
  pull_request:
    branches:
      - main

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: action/checkout@v4

        - name: Setup JDK environment
          uses: actions/setup-java@v1
          with:
            java-version: '11'

        - name: Build Debug variant
          run: ./gradlew assembleDebug

        - name: Run static code analysis
          run: ./gradlew detekt
